name: CI DEPLOY

#Trigger condition: after the push to master branch
on:
  push:
    branches:
      - master

#Mission
jobs:
  build-and-deploy:
    #Server environment: latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      #Pull code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      #Generating static files
      - name: Build
        run: npm install && npm run build

      #Deploy to GitHub pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/ukbg
